config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :trips, only: [:new, :index, :create]
  root 'trips#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trip.rb
class Trip < ApplicationRecord
  validates :tanking_cost, presence: true, if: :cost_unavailable?
  validates :trip_distance, presence: true, if: ->(trip) { trip.fuel_cost || trip.avg_consumption }
  validates :fuel_cost, presence: true, if: ->(trip) { trip.avg_consumption || trip.trip_distance }
  validates :avg_consumption, presence: true, if: ->(trip) { trip.fuel_cost || trip.trip_distance }
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, allow_blank: true

  belongs_to :user, optional: true

  before_save :calculate_cost_per_person
  after_save :send_email

  mount_uploader :invoice, InvoiceUploader

  private

  def send_email
    return true unless email.present?
    TripSplitterMailSender.perform_later(self.id)
  end

  def calculate_cost_per_person
    CostPerPersonCalculator.new(self).call
  end

  def cost_unavailable?
    trip_distance.nil? && fuel_cost.nil? && avg_consumption.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_avatarable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :trips

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout :determine_layout

  private

  def determine_layout
    current_user ? 'user' : 'guest_user'
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  expose_decorated(:trip)
  expose_decorated(:trips)  { get_trips }

  def new
    trip = Trip.new
    trip.invoice = params[:file]
  end

  def create
    trip.save
    render :new
  end

  private

  def calculate_cost_per_person
    CostPerPersonCalculator.new(self).call
  end

  def get_trips
    if current_user.admin?
      collection = Trip.all
    else
      collection = current_user.trips
    end
  end

  def trip_params
    params.require(:trip).permit(
      :people_count,
      :driver_included,
      :trip_distance,
      :fuel_cost,
      :avg_consumption,
      :tanking_cost,
      :email,
      :trip_name,
      :user_id,
      :invoice
      )
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_guest_user_tips.html.erb
<div id="jmbTrn" class="jumbotron">
  <h1>Welcome, guest!</h1>
  <p class="lead">
    You must sign in or sign up before you can access saving and listing your trips.
  </p>
  <div class="row-fluid">
    <div class="span6">
      <%= link_to "Sign In", new_user_session_path, :class => "btn btn-success" %>
    </div>
    <p></p>
    <div class="span6">
      <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-success" %>
    </div>
  </div>
</div>

app/views/layouts/application.haml
!!!
%html
  %head
    %meta(content="text/html; charset=UTF-8" http-equiv="Content-Type")/
    %title Tripsplitter
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/layouts/guest_user.haml
!!!
%html
  %head
    %meta(content='text/html; charset=UTF-8' http-equiv='Content-Type')/
    %title Tripsplitter
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container-narrow
      .navbar-header
        %span.btn.btn-info= link_to 'Tripsplitter', root_path
        %span= t('.motto')
        %b= t('.welcome_guest')
        %span#session_options.container-narrow.float-right
          %span= link_to t('.sign_in'), new_user_session_path, class: 'btn btn-large btn-info'
          %span= link_to t('.sign_up'), new_user_registration_path, class: 'btn btn-large btn-info'
        #jmbTrn.jumbotron
          %h1= t('.welcome_guest')
          %p.lead= t('.warning')
          .row-fluid
            .span6
              = link_to t('.sign_in'), new_user_session_path, class: 'btn btn-success'
            %p
            .span6
              = link_to t('.sign_up'), new_user_registration_path, class: 'btn btn-success'
        %hr/
        = yield

app/views/layouts/user.haml
!!!
%html
  %head
    %meta(content="text/html; charset=UTF-8" http-equiv="Content-Type")/
    %title Tripsplitter
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container-narrow
      .navbar-header
        %span.btn.btn-info= link_to t('.tripsplitter'), root_path
        %span= t('.motto')
        %b= t('.welcome', email: current_user.email)
        - if current_user.try(:admin?)
          %b= t('.admin_rights')
        %span#session_options.container-narrow.float-right
          %span= link_to t('.sign_out'), destroy_user_session_path, method: :delete, class: 'btn btn-large btn-danger'
        %hr/
        = yield

app/views/shared/_guest_user_tips.html.erb
<div id="jmbTrn" class="jumbotron">
  <h1>Welcome, guest!</h1>
  <p class="lead">
    You must sign in or sign up before you can access saving and listing your trips.
  </p>
  <div class="row-fluid">
    <div class="span6">
      <%= link_to "Sign In", new_user_session_path, :class => "btn btn-success" %>
    </div>
    <div class="span6">
      <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-success" %>
    </div>
  </div>
</div>

app/views/trips/index.haml
- if user_signed_in?
  - if trips.present?
    %table.table-striped.table-hover.table-condensed.table-bordered
      %tbody
        %tr
          %th= t('trip_name')
          %th= t('people_count')
          %th= t('driver_included')
          %th= t('trip_distance')
          %th= t('fuel_cost')
          %th= t('avg_consumption')
          %th= t('tanking_cost')
          %th.b= t('.cost_per_person')
          %th= t('email')
          %th= t('invoice')
          - if current_user.try(:admin?)
            %th= t('.user_id')
            %th= t('.user_email')
            %th= t('.created_at')

        - trips.each do |trip|
          %tr
            %td= trip.trip_name
            %td= trip.people_count
            %td= trip.driver_included
            %td= trip.trip_distance
            %td= trip.formatted_amount(:fuel_cost)
            %td= trip.avg_consumption
            %td= trip.formatted_amount(:tanking_cost)
            %td= trip.formatted_amount(:cost_per_person)
            %td= trip.email
            -if trip.invoice?
              %td
                = link_to (fa_icon "download"), trip.try(:invoice).url, style: 'color:#FFFFFF;'
            -else
              %td= ""
            - if current_user.try(:admin?)
              %td= trip.user_id
              %td= trip.user.try(:email)
              %td= trip.formatted_date(:created_at)
  .container-fluid
    %br
    %br
      = button_to t('.new_calculation'), new_trip_path, class: 'btn btn-info calculate-btn', method: :get

app/views/trips/new.haml
- if trip.errors.any?
  #error_explanation
  .alert.alert-danger
    %h5
      = pluralize(trip.errors.count, "error")
      prohibited this trip from being saved:
    %ul
      - trip.errors.full_messages.each do |message|
        %li= message

- if trip.cost_per_person
  .container
    .form-group.form-horizontal
      .card.card-inverse.card-success.text-xs-center
        .card-block
          %blockquote.card-blockquote
            %p
            %footer
              = t('.cost_per_person')
              = number_with_precision(trip.cost_per_person, precision: 2)

              - if trip.driver_included?
                = t('.driver_participation')
              - else
                = t('.driver_free')
  .container
    = button_to t('.new_calculation'), new_trip_path, class: 'btn btn-info calculate-btn', method: :get
    %br
      - if user_signed_in?
        = button_to t('.show_all_trips'), trips_path, class: 'btn btn-info calculate-btn', method: :get

.container
  .form-group.form-horizontal
    = simple_form_for trip, url: trips_path do |f|
      = f.hidden_field :user_id, value: current_user.try(:id)
      %label
      = f.input :trip_name, as: :string, input_html: { placeholder: t('.optional'), autofocus: true }
      %label
      = t('.people_count')
      = f.input :people_count, input_html: { min: 1 }, label: false, as: :integer
      %label
      = t('.driver_included')
      = f.input :driver_included, class: 'cr-icon fa fa-check', label: false, as: :boolean
      %label
      = t('.trip_distance')
      = f.input :trip_distance, input_html: { min: 1 }, label: false, as: :integer
      %label
      = t('.fuel_cost')
      = f.input :fuel_cost, input_html: { min: 1 }, label: false, as: :decimal
      %label
      = t('.avg_consumption')
      = f.input :avg_consumption, input_html: { min: 1 }, label: false, as: :decimal
      %label
      = t('.tanking_cost')
      = f.input :tanking_cost, input_html: { min: 1 }, label: false, as: :decimal
      - if user_signed_in?
        = t('.invoice')
        %p
        = f.file_field :invoice
        %p
      %label
        = f.input :email, as: :string, input_html: { placeholder: t('.optional'), autofocus: true }
        = f.submit t('.submit'), class: 'btn btn-info calculate-btn', disabled: trip.cost_per_person?

- if user_signed_in?
  .container
    = button_to t('.show_all_trips'), trips_path, class: 'btn btn-info calculate-btn', method: :get